export const DICTIONARY = {
  hiragana: [
    { romanji: 'ka', kana: 'か' },
    { romanji: 'ke', kana: 'け' },
    { romanji: 'ki', kana: 'き' },
    { romanji: 'ko', kana: 'こ' },
    { romanji: 'ku', kana: 'く' },
    { romanji: 'sa', kana: 'さ' },
    { romanji: 'se', kana: 'せ' },
    { romanji: 'shi', kana: 'し' },
    { romanji: 'so', kana: 'そ' },
    { romanji: 'su', kana: 'す' },
    { romanji: 'ta', kana: 'た' },
    { romanji: 'te', kana: 'て' },
    { romanji: 'chi', kana: 'ち' },
    { romanji: 'to', kana: 'と' },
    { romanji: 'tsu', kana: 'つ' },
    { romanji: 'na', kana: 'な' },
    { romanji: 'ne', kana: 'ね' },
    { romanji: 'ni', kana: 'に' },
    { romanji: 'no', kana: 'の' },
    { romanji: 'nu', kana: 'ぬ' },
    { romanji: 'ha', kana: 'は' },
    { romanji: 'he', kana: 'へ' },
    { romanji: 'hi', kana: 'ひ' },
    { romanji: 'ho', kana: 'ほ' },
    { romanji: 'fu', kana: 'ふ' },
  ],
  katakana: [
    { romanji: 'ka', kana: 'カ' },
    { romanji: 'ke', kana: 'ケ' },
    { romanji: 'ki', kana: 'キ' },
    { romanji: 'ko', kana: 'コ' },
    { romanji: 'ku', kana: 'ク' },
    { romanji: 'sa', kana: 'サ' },
    { romanji: 'se', kana: 'セ' },
    { romanji: 'shi', kana: 'シ' },
    { romanji: 'so', kana: 'ソ' },
    { romanji: 'su', kana: 'ス' },
    { romanji: 'ta', kana: 'タ' },
    { romanji: 'te', kana: 'テ' },
    { romanji: 'chi', kana: 'チ' },
    { romanji: 'to', kana: 'ト' },
    { romanji: 'tsu', kana: 'ツ' },
    { romanji: 'na', kana: 'ナ' },
    { romanji: 'ne', kana: 'ネ' },
    { romanji: 'ni', kana: 'ニ' },
    { romanji: 'no', kana: 'ノ' },
    { romanji: 'nu', kana: 'ヌ' },
    { romanji: 'ha', kana: 'ハ' },
    { romanji: 'he', kana: 'へ' },
    { romanji: 'hi', kana: 'ヒ' },
    { romanji: 'ho', kana: 'ホ' },
    { romanji: 'fu', kana: 'フ' },
  ],
}

export const CORRECT_PHRASES = ['Nice job!', "That's right!", 'Keep going!']

export const ENCOURAGEMENT_PHRASES = ["Let's try again!"]
